### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by ghost** [toorop/ovh-cli#10]
Nothing seems to be working, I've downloaded the ovh command and it asked me to export a consumer key I did it, then when I try to add something in the firewall (to allow port:  ./ovh fw addRule myIPBLOCK IP --sequence 0 --action allow --toPort 7777 --protocol udp) it says Incorrect Usage. 

When I try to do something else like " ovh ip block list " I get "Error: 403 ForbiddenNOT_CREDENTIALThis credential does not exist
" 

I don't think that I'm the problem? Am I?

**Comment by toorop** [comment]
>  ./ovh fw addRule myIPBLOCK IP --sequence 0 --action allow --toPort 7777 --protocol udp it says Incorrect Usage.

Try like in doc: -> "ovh fw addRule [--flag...] IPBLOCK IP"
 ./ovh fw addRule  --sequence 0 --action allow --toPort 7777 --protocol udp myIPBLOCK IP

>  403 ForbiddenNOT_CREDENTIAL This credential does not exist

The credentail you use doesn't not exist for OVH or maybe you did not authorize 'IP endpoint" for your current cred

**Comment by ghost** [comment]
Thanks for the answer, It was the credential problem, but now I fixed that and I ran " ./ovh ip block list " and it works, but adding a rule to the firewall doesn't work still. I paste the command you sent and changed to my ip block and IP, but I still get "Incorrect Usage"

**Comment by toorop** [comment]
Maybe ovh API has changed since i release this code...
I'm sorry but i have not time now to check OVH doc and do some test (and to be honest i'm not motivated, working with OVH API is a real torture)

**Comment by ghost** [comment]
This is the output of only  ./ovh fw

`./ovh fw
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x8138e0e]

goroutine 1 [running]:
github.com/codegangsta/cli.HandleAction.func1(0x88bed28)
        /home/toorop/projects/go/src/github.com/codegangsta/cli/app.go:478 +0x1dc
panic(0x830fa00, 0x85bbe88)
        /home/toorop/projects/gosrc/go/src/runtime/panic.go:513 +0x16d
github.com/codegangsta/cli.HandleAction(0x0, 0x0, 0x8810280, 0x0, 0x0)
        /home/toorop/projects/go/src/github.com/codegangsta/cli/app.go:483 +0x7e
github.com/codegangsta/cli.Command.Run(0x834c944, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8351612, 0x13, 0x0, ...)
        /home/toorop/projects/go/src/github.com/codegangsta/cli/command.go:186 +0x843
github.com/codegangsta/cli.(*App).Run(0x88d8270, 0x880c030, 0x2, 0x2, 0x0, 0x0)
        /home/toorop/projects/go/src/github.com/codegangsta/cli/app.go:240 +0x43f
main.main()
        /home/toorop/projects/go/src/github.com/toorop/ovh-cli/ovh.go:202 +0x4f0
`

**Comment by ghost** [comment]
I'm sorry for bothering you then, thanks for the help, but do you know is there any other ovh-cli that has firewall commands? Thanks for the help again.

**Comment by asquelt** [comment]
@JackZara how did you get past NOT_CREDENTIAL error?
My existing accounts still work but I have exactly the same problem with new account.

ok, I've managed to get it going. There's a bug in auth.go:

```
	body := "{\"accessRules\":[{\"method\":\"GET\",\"path\":\"/*\"},{\"method\":\"POST\",\"path\":\"/*\"},{\"method\":\"DELETE\",\"path\":\"/*\"},{\"method\":\"PUT\",\"path\":\"/*\"},{\"method\":\"DELETE\",\"path\":\"/*\"} ]}"
```

(notice duplicated DELETE access rule)
